# Generated by Django 4.1.2 on 2023-01-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complated',
            new_name='completed',
        ),
    ]
