# Generated by Django 4.1.2 on 2023-01-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_complated_order_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='complete',
        ),
    ]
